package com.jasper_report.model.Enum;

public enum FontStyles {

    ARIAL_SMALL,ARIAL_MEDIUM,ARIAL_BIG,
    TIMES_NEW_ROMAN_SMALL,TIMES_NEW_ROMAN_MEDIUM,TIMES_NEW_ROMAN_BIG,
    COURIER_NEW_SMALL,COURIER_NEW_MEDIUM,COURIER_NEW_BIG,
    COMIC_SANS_SMALL,COMIC_SANS_MEDIUM,COMIC_SANS_BIG,
    GEORGIA,_SMALL,GEORGIA_MEDIUM,GEORGIA_BIG,
    VERDANA_SMALL,VERDANA_MEDIUM,VERDANA_BIG
}